class Cars:
    color="Red"
    model="xuv"
    price=33442
car1=Cars()
car2=Cars()
car3=Cars()
print(car1.color)
print(car2.color)
print(car3.color)
car3.color="Green"
print(car3.color)
print(car1.model)
print(car2.model)
print(car3.model)
car2.color="Blue"
print(car2.color)
print(car1.price)
print(car2.price)
print(car3.price)
car1.color="Yellow"
print(car1.color)